import {expect, runBun, signIn, test} from "../../../../../scripts/e2e/fixtures";
import {browseActor, browseDirector, browseGem, browseMovies} from "../lists/collections/-browse.data";


test("filters job titles by viewer membership with shared sorting and preserves pagination criteria", async ({ page }) => {
    await runBun(["src/routes/_main/_viewer/lists/collections/-browse.fixtures.ts"]);
    await page.goto(`/details/movies/actor/${encodeURIComponent(browseActor)}`);
    const controls = page.getByRole("group", { name: "Media browsing controls", exact: true });
    const results = page.locator('[aria-label="Browsing results and filters"]');
    const search = page.getByRole("searchbox", { name: "Search these titles", exact: true });
    const sort = controls.getByRole("combobox", { name: "Sort these titles", exact: true });
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(controls.getByRole("combobox", { name: "Filter by list", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("combobox", { name: "Filter by status", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("button", { name: "Filters", exact: true })).toHaveCount(0);
    await sort.click();
    await expect(page.getByRole("option", { name: "Title A-Z", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: "TMDB Rating +", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: /^(Rating [+-]|Recently |Added First|Added Oldest|Modified First|Re-[Ww]atched|Redo|Playtime|Your rating|Date added)/ })).toHaveCount(0);
    await page.keyboard.press("Escape");

    await page.goto(`/details/movies/creator/${encodeURIComponent(browseDirector)}`);
    await expect(page.getByText("Director · Movies", { exact: true })).toBeVisible();
    await expect(page.getByText(`Movies directed by ${browseDirector}.`, { exact: true })).toBeVisible();
    await expect(search).toHaveAttribute("placeholder", "Search this filmography...");
    await signIn(page, "stranger");
    await page.goto(`/details/movies/actor/${encodeURIComponent(browseActor)}`);
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(controls.getByRole("combobox", { name: "Filter by status", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("button", { name: "Filters", exact: true })).toHaveCount(0);
    await expect(page.getByRole("link", { name: `View ${browseGem}`, exact: true })).toHaveCount(0);
    const library = controls.getByRole("combobox", { name: "Filter by list", exact: true });
    await library.click();
    await page.getByRole("option", { name: "In my list", exact: true }).click();
    await expect(results.getByText("2 titles", { exact: true })).toBeVisible();
    await sort.click();
    await expect(page.getByRole("option", { name: "Release Date +", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: /^(Rating [+-]|Recently |Added First|Added Oldest|Modified First|Re-[Ww]atched|Redo|Playtime|Your rating|Date added)/ })).toHaveCount(0);
    await page.getByRole("option", { name: "Title Z-A", exact: true }).click();
    await controls.getByRole("button", { name: "Table view", exact: true }).click();
    const table = page.getByRole("table", { name: "Media results", exact: true });
    await expect(table.getByRole("row").nth(1)).toContainText(browseGem);
    await expect(table.locator("img")).toHaveCount(0);
    await expect(table.getByRole("columnheader", { name: "In your list", exact: true })).toBeVisible();
    await expect(table.getByRole("columnheader", { name: /^(Status|Information|Rating \/ favorite|Added|Updated)$/ })).toHaveCount(0);
    await expect(table.getByRole("row").nth(1)).toContainText("Yes");
    await search.fill(browseGem);
    await expect(results.getByText("1 title", { exact: true })).toBeVisible();
    await expect(table.getByText(browseGem, { exact: true })).toBeVisible();
    await expect(table.getByText(browseMovies[28].name, { exact: true })).toHaveCount(0);
    await results.getByRole("button", { name: `Remove Search: ${browseGem}`, exact: true }).click();
    await expect(search).toHaveValue("");
    await expect(results.getByText("2 titles", { exact: true })).toBeVisible();
    await library.click();
    await page.getByRole("option", { name: "Not in my list", exact: true }).click();
    await expect(results.getByText("28 titles", { exact: true })).toBeVisible();
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[27].name);
    await expect(table.getByText(browseGem, { exact: true })).toHaveCount(0);
    await results.getByRole("button", { name: "Reset filters", exact: true }).click();
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(sort).toContainText("Release Date -");
    await expect(library).toContainText("All titles");
    await expect(results.getByRole("button", { name: "Reset filters", exact: true })).toHaveCount(0);
    await sort.click();
    await page.getByRole("option", { name: "Title Z-A", exact: true }).click();
    await expect(page).toHaveURL(url => url.searchParams.get("sorting") === "title_desc" && !url.searchParams.has("search"));
    await results.getByRole("button", { name: "Reset filters", exact: true }).click();
    await expect(sort).toContainText("Release Date -");
    await expect(page).toHaveURL(url => !url.searchParams.has("sorting"));
    await expect(results.getByRole("button", { name: "Reset filters", exact: true })).toHaveCount(0);
    await search.fill("Catalogue");
    await expect(results.getByText("29 titles", { exact: true })).toBeVisible();
    await controls.getByRole("combobox", { name: "Sort these titles", exact: true }).click();
    await page.getByRole("option", { name: "Title Z-A", exact: true }).click();
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[28].name);
    await page.getByRole("button", { name: "Go to page 2", exact: true }).click();
    await expect(page).toHaveURL(url => url.searchParams.get("page") === "2" && url.searchParams.get("search") === "Catalogue" && url.searchParams.get("sorting") === "title_desc" && url.searchParams.get("display") === "table");
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[4].name);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.reload();
    await expect(search).toHaveValue("Catalogue");
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[4].name);
});
