DROP TABLE `user_media_activity`;--> statement-breakpoint
DROP TABLE `user_media_settings`;--> statement-breakpoint
DROP TABLE `user_media_stats_history`;--> statement-breakpoint
DROP TABLE `user_media_update`;--> statement-breakpoint
DROP TABLE `series_actors`;--> statement-breakpoint
DROP TABLE `series_episodes_per_season`;--> statement-breakpoint
DROP TABLE `series_genre`;--> statement-breakpoint
DROP TABLE `series_list`;--> statement-breakpoint
DROP TABLE `series_network`;--> statement-breakpoint
DROP TABLE `series_tags`;--> statement-breakpoint
DROP TABLE `series`;--> statement-breakpoint
DROP TABLE `anime_actors`;--> statement-breakpoint
DROP TABLE `anime_episodes_per_season`;--> statement-breakpoint
DROP TABLE `anime_genre`;--> statement-breakpoint
DROP TABLE `anime_list`;--> statement-breakpoint
DROP TABLE `anime_network`;--> statement-breakpoint
DROP TABLE `anime_tags`;--> statement-breakpoint
DROP TABLE `anime`;--> statement-breakpoint
DROP TABLE `movies_actors`;--> statement-breakpoint
DROP TABLE `movies_genre`;--> statement-breakpoint
DROP TABLE `movies_list`;--> statement-breakpoint
DROP TABLE `movies_tags`;--> statement-breakpoint
DROP TABLE `movies`;--> statement-breakpoint
DROP TABLE `games_companies`;--> statement-breakpoint
DROP TABLE `games_genre`;--> statement-breakpoint
DROP TABLE `games_list`;--> statement-breakpoint
DROP TABLE `games_platforms`;--> statement-breakpoint
DROP TABLE `games_tags`;--> statement-breakpoint
DROP TABLE `games`;--> statement-breakpoint
DROP TABLE `books_authors`;--> statement-breakpoint
DROP TABLE `books_genre`;--> statement-breakpoint
DROP TABLE `books_list`;--> statement-breakpoint
DROP TABLE `books_tags`;--> statement-breakpoint
DROP TABLE `books`;--> statement-breakpoint
DROP TABLE `manga_authors`;--> statement-breakpoint
DROP TABLE `manga_genre`;--> statement-breakpoint
DROP TABLE `manga_list`;--> statement-breakpoint
DROP TABLE `manga_tags`;--> statement-breakpoint
DROP TABLE `manga`;--> statement-breakpoint
DROP TABLE `collection_items`;--> statement-breakpoint
DROP TABLE `collection_likes`;--> statement-breakpoint
DROP TABLE `collections`;
