import {Generator, getConfig} from "@tanstack/router-generator";


// Match router options and Start registration generated by vite.config.ts
const config = getConfig({
    semicolons: true,
    quoteStyle: "double",
    routeTreeFileFooter: [
        'import type { getRouter } from "./router.tsx";',
        'import type { startInstance } from "./start.ts";',
        'declare module "@tanstack/react-start" {',
        '  interface Register {',
        '    ssr: true;',
        '    router: Awaited<ReturnType<typeof getRouter>>;',
        '    config: Awaited<ReturnType<typeof startInstance.getOptions>>;',
        '  }',
        '}',
    ],
}, process.cwd());


await new Generator({ config, root: process.cwd() }).run();
