import {publicCollection} from "../../../../../scripts/e2e/data";
import {expect, runBun, signIn, test} from "../../../../../scripts/e2e/fixtures";
import {browseGem, browseMovies, browseNote} from "./-browse.data";


test("browses a ranked collection with shared sorting, preserves notes and tailors guest and viewer controls", async ({ page }) => {
    await runBun(["src/routes/_main/_viewer/collections/-browse.fixtures.ts"]);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`/collections/${publicCollection.id}`);
    const controls = page.getByRole("group", { name: "Media browsing controls", exact: true });
    const results = page.locator('[aria-label="Browsing results and filters"]');
    const search = page.getByRole("searchbox", { name: "Search this collection", exact: true });
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: `View ${browseMovies[0].name}`, exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: `View ${browseGem}`, exact: true })).toHaveCount(0);
    await expect(controls.getByRole("combobox", { name: "Filter by library", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("combobox", { name: "Filter by status", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("button", { name: "Filters", exact: true })).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

    await search.fill(browseGem);
    await expect(results.getByText("1 title", { exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: `View ${browseGem}`, exact: true })).toBeVisible();
    await expect(page.getByText("#30", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "View comment", exact: true }).click();
    await expect(page.getByText(browseNote, { exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    await controls.getByRole("button", { name: "Table view", exact: true }).click();
    const table = page.getByRole("table", { name: "Media results", exact: true });
    await expect(table).toBeVisible();
    await expect(table.locator("img")).toHaveCount(0);
    await expect(table.getByRole("columnheader", { name: "Rank", exact: true })).toBeVisible();
    await expect(table.getByRole("columnheader", { name: "Status", exact: true })).toHaveCount(0);
    await expect(table.getByText("#30", { exact: true })).toBeVisible();
    await table.getByRole("button", { name: "View comment", exact: true }).click();
    await expect(page.getByText(browseNote, { exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await results.getByRole("button", { name: "Reset filters", exact: true }).click();
    await expect(search).toHaveValue("");
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();

    await search.fill(browseGem);
    await expect(results.getByText("1 title", { exact: true })).toBeVisible();
    await results.getByRole("button", { name: `Remove Search: ${browseGem}`, exact: true }).click();
    await expect(search).toHaveValue("");
    const sort = controls.getByRole("combobox", { name: "Sort collection titles", exact: true });
    await sort.click();
    await expect(page.getByRole("option", { name: "Collection order", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: "Release Date +", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: "TMDB Rating +", exact: true })).toBeVisible();
    await expect(page.getByRole("option", { name: /^(Rating [+-]|Recently |Added First|Added Oldest|Modified First|Re-[Ww]atched|Redo|Playtime|Your rating|Date added)/ })).toHaveCount(0);
    await page.getByRole("option", { name: "Title Z-A", exact: true }).click();
    await expect(table.getByRole("row").nth(1)).toContainText(browseGem);
    await expect(table.getByRole("row").nth(1)).toContainText("#30");

    await signIn(page, "stranger");
    await page.goto(`/collections/${publicCollection.id}`);
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(controls.getByRole("combobox", { name: "Filter by status", exact: true })).toHaveCount(0);
    await expect(controls.getByRole("button", { name: "Filters", exact: true })).toHaveCount(0);
    const library = controls.getByRole("combobox", { name: "Filter by library", exact: true });
    await library.click();
    await page.getByRole("option", { name: "In my list", exact: true }).click();
    await expect(results.getByText("2 titles", { exact: true })).toBeVisible();
    await controls.getByRole("button", { name: "Table view", exact: true }).click();
    await expect(table.getByText(browseGem, { exact: true })).toBeVisible();
    await expect(table.getByText("#30", { exact: true })).toBeVisible();
    await table.getByRole("button", { name: "View comment", exact: true }).click();
    await expect(page.getByText(browseNote, { exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    await sort.click();
    await expect(page.getByRole("option", { name: /^(Rating [+-]|Recently |Added First|Added Oldest|Modified First|Re-[Ww]atched|Redo|Playtime|Your rating|Date added)/ })).toHaveCount(0);
    await page.getByRole("option", { name: "Title Z-A", exact: true }).click();
    await expect(table.getByRole("row").nth(1)).toContainText(browseGem);
    await expect(table.getByRole("row").nth(1)).toContainText("9");
    await library.click();
    await page.getByRole("option", { name: "Not in my list", exact: true }).click();
    await expect(results.getByText("28 titles", { exact: true })).toBeVisible();
    await expect(table.getByText(browseGem, { exact: true })).toHaveCount(0);
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[27].name);
    await search.fill("Catalogue");
    await expect(results.getByText("28 titles", { exact: true })).toBeVisible();
    await expect(page).toHaveURL(url => url.searchParams.get("search") === "Catalogue");
    await page.getByRole("button", { name: "Go to page 2", exact: true }).click();
    await expect(page).toHaveURL(url => url.searchParams.get("page") === "2" && url.searchParams.get("library") === "out" && url.searchParams.get("search") === "Catalogue" && url.searchParams.get("sorting") === "title_desc" && url.searchParams.get("display") === "table");
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[3].name);
    await results.getByRole("button", { name: "Reset filters", exact: true }).click();
    await expect(search).toHaveValue("");
    await expect(results.getByText("30 titles", { exact: true })).toBeVisible();
    await expect(library).toContainText("All titles");
    await expect(sort).toContainText("Collection order");
    await expect(table.getByRole("row").nth(1)).toContainText(browseMovies[0].name);
    await expect(table.getByRole("row").nth(1)).toContainText("#1");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
